### ISSUE TITLE
Tote Links

### ISSUE THREAD

**Issue by baccenfutter** [programmfabrik/easydb-documentation#1]
Die deutsche `README.md` verweist im Teil `Überblick` mit einem Link `Releases` auf `https://github.com/programmfabrik/easydb-documentation/blob/master/releases/releases.html` => 404

**Comment by baccenfutter** [comment]
Genauer gesagt, führen fast alle Links auf der Seite zu einem 404.

**Comment by romanglom** [comment]
You are right. The README has old links. EasyDB docs is here -> https://docs.easydb.de

**Comment by baccenfutter** [comment]
Many Github projects add a clickable link to the topics sectio where this repo only says "easydb documentation". Perhaps we could add that to make clear where the production instance of the docs are available?

**Comment by baccenfutter** [comment]
thx
