### ISSUE TITLE
content/sysadmin/installation/prod_clone.en.md: Maybe also recommend cloning the ES index?

### ISSUE THREAD

**Issue by moschlar** [programmfabrik/easydb-documentation#13]
Recently, when re-creating a cloned instances, I forgot about the ES index and thinking about it, I thought it would probably more efficient to just clone it too, when cloning an instance:

`curl -X POST "easydb-elasticsearch.docker:9200/easydb5/_clone/easydb5-clone?pretty"`
or
`curl -X POST "easydb-elasticsearch.docker:9200/$SRC_DB_NAME/_clone/$DST_DB_NAME?pretty"`

cf. https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-clone-index.html

**Comment by KlausThornProgrammfabrik** [comment]
Dear moschlar,

thanks for sour suggestion!
