### ISSUE TITLE
CustomDataType Plugin search mapping Doku

### ISSUE THREAD

**Issue by isgrim** [programmfabrik/easydb-documentation#3]
Hallo Programmfabrik Team,

In der Doku und so wie die CustomDataType Plugins implementiert sind, wird momentan das 
Search Mapping benutzt so wie hier beschrieben:
https://docs.easydb.de/en/technical/plugins/customdatatype/customdatatype.html#search-mapping

Aber gleichzeitig gibt auch das `_fulltext` Feld:
https://docs.easydb.de/en/technical/plugins/customdatatype/customdatatype.html#general-keys

Mir ist leider nicht klar wie der Zusammenhang ist. 
Könntet ihr das kurz erklären?

Liebe Grüße,

Nils Weiher

**Comment by isgrim** [comment]
Hallo Martin,

entschuldige bitte, ich habe mich leider nicht klar ausgedrückt. Ich meinte:
Was ist der Unterschied, wenn ich ein Feld in der YAML Plugin-Konfiguration unter `mapping` Konfiguriere oder einfach den Inhalt in das `_fulltext` Feld übernehme?

Werden sie dann anders von ElasticSearch indiziert?

Liebe Grüße,

Nils

**Comment by martinrode** [comment]
Für die Volltext-Suche ist `_fulltext` ausreichend. Wenn du Facet-Support brauchst, dann musst du im Mapping die Felder auflisten die du dort haben willst. Siehe das Custom-Data-Type-Link Plugin von uns. Dort wird über die TLD facetiert.

**Comment by isgrim** [comment]
Ah danke, das ist super. Habe gehofft, dass es so ist.

Vielen Dank Martin, ich schließe das Issue wieder!
